# -*- coding: utf-8 -*-
"""chatbot_+ _model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gHHAhf3PH5nYgQkWOcub48HYTMNAJHkk
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pyTelegrambotapi
# %pip install wikipedia

import telebot
import wikipedia

print("pyTelegramBotAPI and wikipedia have been installed and imported successfully!")

from transformers import pipeline

qNa = pipeline('question-answering')

bot = telebot.TeleBot(TOKEN)
talk = 0
su = ''

@bot.message_handler(func=lambda message:True)
def answer_the_question(message):

  global talk
  global su

  if talk == 0:
    bot.reply_to(message, 'tell me a subject you wnated to talk about')
    talk = 1
    return

  if talk == 1:
    results = wikipedia.search(message.text)
    summary = wikipedia.summary(results[0])
    su = summary
    talk = 2
    return

  if talk == 2:
    a = qNa(context=su, question=message.text)
    print(a)
    bot.reply_to(message, list(a.values())[3])
    talk = 0
    return

bot.infinity_polling()